### ISSUE TITLE
Publishing on f-droid.org?

### ISSUE THREAD

**Issue by Gemba** [BenoitDuffez/AndroidCupsPrint#12]
Maybe this is already on your roadmap? The Jon Freeman Version is in f-droid but quite outdated and unmaintained.

**Comment by BenoitDuffez** [comment]
I didn't know this website. I registered but the publication process seems rather vague. I'll definitely do it though!

**Comment by BenoitDuffez** [comment]
I installed fdroid on my machine, I'll push it there once the current master is ready for production (after which I'll definitely create a develop branch).

**Comment by BenoitDuffez** [comment]
I have diverged the `master` at its current state into a new `develop` branch. Please continue all work on that branch. Sorry for the force push.

I have reverted `master` to the commit ID that is currently published on the Play Store, so that it respects the message in the README file that says that `master` is always the code that's currently available on the Play Store.

The app [was submitted](https://gitlab.com/fdroid/fdroiddata/merge_requests/1259) to f-droid.

**Comment by Gemba** [comment]
Thanks for promoting to f-droid, and thanks for the dev. branch. With git this is a no brainer to use the branch. :o)

**Comment by theScrabi** [comment]
Hello,

I forked this repository, in order to make it compatible for f-droid (remove google stuff from build scripts):
https://github.com/theScrabi/AndroidCupsPrint

Here is the commit for this app:
https://gitlab.com/fdroid/fdroiddata/merge_requests/1430#note_12109349
But f-droid likes to get the data from upstream, not from a fork.

F-droid release system works with tags. So every time you release a tag with a specific name (like fdroid-1.2) this tag will be cloned build and put into f-droid repository. Please consider an f-droid fork. You can use my [master branch](https://github.com/theScrabi/AndroidCupsPrint) to do that.

**Comment by theScrabi** [comment]
No, I'm giving up, we need a version without *.jar files, this is me trying to acheve this based on the latest release. I'ts just to besed up. Please release an f-droid version, which would be a clean solution:
```
License:LGPLv3
Web Site:https://benoitduffez.github.io/AndroidCupsPrint/
Source Code:https://github.com/BenoitDuffez/AndroidCupsPrint
Issue Tracker:https://github.com/BenoitDuffez/AndroidCupsPrint/issues

Auto Name:AndroidCupsPrint
Summary:This app allows you to print directly from Android to your CUPS server
Description:
Have a local printer shared over CUPS or IPP? Then this app allows you to
directly print to it from your Android device.

This app just provides a Print Service to Android. This means that once it's
installed, you have to enable it from your 'Print' section of the settings app
of you device. Once the service is enabled, the printers are automatically
discovered using the mDNS protocol. You can print anything you want from any
app, as long as the print service is enabled.

Port of cups4j to Android. Original work was created by Jon Freeman, it included
an app that reacts to the SEND intent to print documents.
.

Repo Type:git
Repo:https://github.com/BenoitDuffez/AndroidCupsPrint

Build:1.2,4
    commit=c2e1679cf1fe1a67a252ecca2ed92b7076655477
    subdir=app
    gradle=yes
    prebuild=sed -i -e '3,20d;38,50d;55d;61d' build.gradle && \
       rm libs/cups4jpatched.jar && \
       rm libs/mdnstest2.jar && \
       wget http://mobd.jonbanjo.com/jfcupsprint/downloads/cups4jpatched.zip && \
       unzip cups4jpatched.zip && \
       mv src/ch src/main/java && \
       mv src/org src/main/java && \
       sed -i -e 's/import org.apache.http.conn.ssl.TrustSelfSignedStrategy;//g' src/main/java/org/cups4j/operations/IppOperation.java && \
       sed -i "29 a compile \'org.apache.httpcomponents:httpclient:4.5.2\'" build.gradle && \
       sed -i "29 a compile group: 'javax.xml.bind', name: 'jaxb-api', version: '2.1'" build.gradle && \
       sed -i "29 a compile 'javax.jmdns:jmdns:3.4.1'" build.gradle && \
       sed -i -e 's/com.jmdns/javax.jmdns/g' src/main/java/com/jonbanjo/detect/MdnsServices.java


Auto Update Mode:None
Update Check Mode:RepoManifest
Current Version:1.2
Current Version Code:4 
```

**Comment by BenoitDuffez** [comment]
f-droid is just too much work for me right now. It's also kind of a PITA. I can't wrap my head around all the concepts behind f-droid, the client, the fact that I need to build something, publish it...
I tried to update my metadata file with what you pasted but it's not working.

**Comment by theScrabi** [comment]
Sounds like you try to setup your own repository. Don't do that, I'm trying to bring this into the official repo.
However the only thing that does not work at the moment is the that 's/com.jmdns/javax.jmdns/g' is not working. either com.jmdns.*; Does not work since it cant find that javax.jmdns.*; is seemingly not allowed by java.

**Comment by BenoitDuffez** [comment]
Feel free to submit a PR that would make the repo compatible with fdroid. I understand they don't want any jars but instread links to other fdroid-compatible repositories. This needs (among other things) rework from the cups lib that Jon Freeman originally ported to Android.

**Comment by theScrabi** [comment]
I've already tried to compile it, and everything seemed to work, only jmdns didn't want to link correct.

**Comment by BenoitDuffez** [comment]
I merged #15 into a new branch

**Comment by theScrabi** [comment]
can you please make an fdroid-1.2 tag on that branch.

**Comment by theScrabi** [comment]
Although never mind.

**Comment by BenoitDuffez** [comment]
Well? I was about to do it :)

**Comment by theScrabi** [comment]
So [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/1451) is the commit to the main repository. I still w8 for merge.

**Comment by BenoitDuffez** [comment]
Nice. Thanks a lot. I'll close when it's ready then.

**Comment by theScrabi** [comment]
[Here](https://f-droid.org/repository/browse/?fdid=io.github.benoitduffez.cupsprint) it is, and it works like a charm :)

**Comment by BenoitDuffez** [comment]
Nice! Thank you very much.
