### ISSUE TITLE
CUPS encryption.

### ISSUE THREAD

**Issue by thegala** [BenoitDuffez/AndroidCupsPrint#175]
When selecting any Android Cups printer i got error.

> This printer isn't available right now.

When looking logs on my server i found:

>  [Client 968] Unable to encrypt connection: A TLS fatal alert has been received.

Does this application enables encryption when talking to CUPS server?
Is there anyway to enable it?

**Comment by BenoitDuffez** [comment]
It is enabled by default and mandatory on most Android versions. If you use avahi/zeroconf/bonjour you should ensure the advertised address is the secure one. Otherwise you could disable the non-secure interface in cups or set up a redirection.

I hope this helps. I'm closing as not an issue but remain available for comment of course!
