### ISSUE TITLE
Non-stop Searching for printers

### ISSUE THREAD

**Issue by whbjr** [BenoitDuffez/AndroidCupsPrint#4]
Turn on service, answer "OK" to security question. Device then starts "Searching for printers" - if there are no appropriate servers on the network, it will search forever. Using the Menu button, add a printer using the format shown, e.g. "http://192.168.1.111:631/printers/hp_thinkjet" (I copied and pasted the text from my working CUPS device). Select "Add printer" and return to the still-searching screen. The printer is not added.

SUGGESTIONS:
1) Add a "Stop" button to the search screen, to allow the service to continue running without searching for new devices.
2) Make the (manual) "Add Printer" function work, whether or not the service is searching for new devices.

**Comment by BenoitDuffez** [comment]
Thanks for your feedback.

1) There is no need, as long as you are on that screen there is a Printer Discovery Session that is active. If you want this to be stopped, leave the screen. There is a circle that spins forever, however in the code there is not much happening. The app will ping all the servers over mDNS, and search for printers on servers that responded.

2) Some users reported it working (including me), some others didn't. I have to work on this to get it 100% working. But before, I have to find some time :)

As 1) is not really an issue, I'm closing this issue as a duplicate of #3 because it fully covers 2).

**Comment by whbjr** [comment]
Thank you - I did not see a list of issues, so I did not know if anyone had
reported this. Best wishes with further development of this very useful
tool!
