### ISSUE TITLE
Update fdroid branch to latest release

### ISSUE THREAD

**Issue by krt16s** [BenoitDuffez/AndroidCupsPrint#69]
https://github.com/BenoitDuffez/AndroidCupsPrint/commits/fdroid hasn't seen the 1.4.x changes, could you update this branch?

**Comment by BenoitDuffez** [comment]
Will do.

Note however that the link to the central fdroid repo is broken, so the binaries there won't get updated.

**Comment by BenoitDuffez** [comment]
Done. Have a look at 4fa4dc96d3135290209a1ab289fd6f70d2c55219.

**Comment by krt16s** [comment]
Thanks for updating. What's the problem with fdroid repo?

**Comment by BenoitDuffez** [comment]
It got too complicated for me, and I wanted to start over from scratch. I nuked the project but now I can't recover. This discussion is still on on #22.

**Comment by BenoitDuffez** [comment]
It seems you made the change? https://gitlab.com/BenoitDuffez/fdroiddata/commit/0717ab97cfae2e6a817bd2d6610e6b1d2d024695

See, I have no fucking clue about how fdroid works:
I have forked the project (again, I deleted it several months ago) and it seems it picked up everything. There is a commit from you 4 hours ago. This makes zero sense to me because my fork didn't exist 10 minutes ago and there is a commit not from me inside it 4 hours ago. WTF?
I mean it's very good that you could do it but as it makes no sense to me I will not be able to update the project myself.

I can keep the fdroid branch up to date though.
Thanks for your contribution!

**Comment by krt16s** [comment]
F-Droid requires two things, a floss upstream source and information about the app and how to build it. When you updated the fdroid branch and closed the issue, I checked if the update was going to build within fdroid and pushed those updated build instructions into fdroid mainline repo (see https://gitlab.com/fdroid/fdroiddata/commit/0717ab97cfae2e6a817bd2d6610e6b1d2d024695). You forked that and so you see my commit in your fork as well.

If you want to update the app yourself, I can remove my commit and add a maintainer note so nobody works on that anymore. That might especially be useful if you dont consider the current state of your fdroid branch ready for release. I am sorry if I rushed things here.

**Comment by BenoitDuffez** [comment]
No that's fine, I thought the only way it could be updated was through a commit on my fork, the one I deleted six months ago.

You didn't rush anything and I'm happy you did it.

I open sourced this app for two reasons: privacy concerns and help from the community. I'm glad you did it. Thanks.

**Comment by BenoitDuffez** [comment]
Is there anything we can do to have the binaries updated?

[The wiki](https://f-droid.org/wiki/index.php?title=io.github.benoitduffez.cupsprint&redirect=no) doesn't talk about the latest version, and neither does [the website](https://f-droid.org/repository/browse/?fdfilter=cups&fdid=io.github.benoitduffez.cupsprint).

**Comment by krt16s** [comment]
It takes some time for those changes to picked up by the buildserver  and do the actual building... as well as it takes time to get it actually signed and published. So the only thing for now is to wait. Sorry about that.

**Comment by BenoitDuffez** [comment]
It's ok. Thanks for the clarification.
