### ISSUE TITLE
Auto discovery creates wrong device urls

### ISSUE THREAD

**Issue by diggy128** [BenoitDuffez/AndroidCupsPrint#84]
Running auto discovery, creates wrong device URLs.
URL is like: http:/192.168.1.1:631/printers/printers/hp

Errors here are: one slash after http and printers show up twice in URL.

After manually editing printers.XML (on rooted nexus 5) printers work again.

Server is CUPS 1.5.4 on OpenSUSE.

**Comment by BenoitDuffez** [comment]
Nice find, I'll fix that.

**Comment by PierluigiZezza** [comment]
Not just that: for instance my printer URI is ipp://localdomain/ipp/print
localdomain IP is that given to the printer by router DHCP
So I have /ipp/print intead of /printers 
Also ipp instead of http on port 631
It would be great to be able to configure the string completely, around the IP discovered by mDNS

**Comment by BenoitDuffez** [comment]
Please create a new issue if you really wish to configure string completely around mDNS results. For now this issue is fixed and I believe this is enough.
